services:
  - type: web
    name: ecomap-backend
    runtime: python
    region: oregon
    plan: free

    buildCommand: >
      apt-get update &&
      apt-get install -y gdal-bin libgdal-dev binutils libproj-dev &&
      pip install --upgrade pip &&
      pip install -r requirements.txt

    startCommand: gunicorn ecomap.wsgi:application
